### ISSUE TITLE
Have a screenshot for your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [Magoc-s/lilith_tf2e#1]
I would love ![image](https://github.com/Magoc-s/lilith_tf2e/assets/46163555/a26da503-3f44-4409-bfbc-12cf0f6fa2c3) to see your GUI (and I'm betting so would other visitors).  Any chance you can drop one into your readme?

**Comment by Magoc-s** [comment]
Hey there! Thanks for the shoulder tap - thats a great idea. I impromptu threw this repo together before heading off to real work and as such its very messy and very incomplete. But I have done as requested! Expect big changes here over the next ~7 days as I progress on the project. Feel free to come back next weekend and see what its looking like then!

**Comment by Magoc-s** [comment]
![gui lobbyviewer](https://github.com/Magoc-s/lilith_tf2e/assets/85176789/b9bd07da-80bd-42d7-bb68-2601f4e73f1f)

Closing the issue with this lovely teaser. I love purple

**Comment by PySimpleGUI** [comment]
Wow!

OMG, I had no clue this beast was lurking in your code!  VERY nice!

![image](https://github.com/Magoc-s/lilith_tf2e/assets/46163555/4145903f-2863-4a2f-9849-9fe55e516668)

Love it!

**Comment by lili7h** [comment]
> I would love for the world to see what you've made if you care to post a screenshot over in the User Screenshots area in the PySimpleGUI Repo.... https://UserScreenshots.PySimpleGUI.org

I would love too! Planning on doing some overhauls and upgrades tonight - then I'll drop the reveal there! :)
